/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MfaChallengeRouteImport } from './routes/mfa-challenge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated/todos'
import { Route as AuthenticatedTipsRouteImport } from './routes/_authenticated/tips'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSnippetsRouteImport } from './routes/_authenticated/snippets'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedRoutinesRouteImport } from './routes/_authenticated/routines'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedFeedsRouteImport } from './routes/_authenticated/feeds'
import { Route as AuthenticatedDiagramsRouteImport } from './routes/_authenticated/diagrams'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCockpitRouteImport } from './routes/_authenticated/cockpit'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksMonthlyTipRouteImport } from './routes/api/public/hooks/monthly-tip'
import { Route as ApiPublicHooksIngestFeedsRouteImport } from './routes/api/public/hooks/ingest-feeds'
import { Route as ApiPublicHooksDailyDigestRouteImport } from './routes/api/public/hooks/daily-digest'
import { Route as ApiPublicHooksDailyDigestStatusRouteImport } from './routes/api/public/hooks/daily-digest.status'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTipsRoute = AuthenticatedTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSnippetsRoute = AuthenticatedSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutinesRoute = AuthenticatedRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedsRoute = AuthenticatedFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagramsRoute = AuthenticatedDiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCockpitRoute = AuthenticatedCockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksMonthlyTipRoute =
  ApiPublicHooksMonthlyTipRouteImport.update({
    id: '/api/public/hooks/monthly-tip',
    path: '/api/public/hooks/monthly-tip',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestFeedsRoute =
  ApiPublicHooksIngestFeedsRouteImport.update({
    id: '/api/public/hooks/ingest-feeds',
    path: '/api/public/hooks/ingest-feeds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyDigestRoute =
  ApiPublicHooksDailyDigestRouteImport.update({
    id: '/api/public/hooks/daily-digest',
    path: '/api/public/hooks/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyDigestStatusRoute =
  ApiPublicHooksDailyDigestStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiPublicHooksDailyDigestRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/cockpit': typeof AuthenticatedCockpitRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagrams': typeof AuthenticatedDiagramsRoute
  '/feeds': typeof AuthenticatedFeedsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/routines': typeof AuthenticatedRoutinesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/snippets': typeof AuthenticatedSnippetsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/tips': typeof AuthenticatedTipsRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRouteWithChildren
  '/api/public/hooks/ingest-feeds': typeof ApiPublicHooksIngestFeedsRoute
  '/api/public/hooks/monthly-tip': typeof ApiPublicHooksMonthlyTipRoute
  '/api/public/hooks/daily-digest/status': typeof ApiPublicHooksDailyDigestStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/cockpit': typeof AuthenticatedCockpitRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagrams': typeof AuthenticatedDiagramsRoute
  '/feeds': typeof AuthenticatedFeedsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/routines': typeof AuthenticatedRoutinesRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/snippets': typeof AuthenticatedSnippetsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/tips': typeof AuthenticatedTipsRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRouteWithChildren
  '/api/public/hooks/ingest-feeds': typeof ApiPublicHooksIngestFeedsRoute
  '/api/public/hooks/monthly-tip': typeof ApiPublicHooksMonthlyTipRoute
  '/api/public/hooks/daily-digest/status': typeof ApiPublicHooksDailyDigestStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/cockpit': typeof AuthenticatedCockpitRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagrams': typeof AuthenticatedDiagramsRoute
  '/_authenticated/feeds': typeof AuthenticatedFeedsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/routines': typeof AuthenticatedRoutinesRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/snippets': typeof AuthenticatedSnippetsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/tips': typeof AuthenticatedTipsRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRouteWithChildren
  '/api/public/hooks/ingest-feeds': typeof ApiPublicHooksIngestFeedsRoute
  '/api/public/hooks/monthly-tip': typeof ApiPublicHooksMonthlyTipRoute
  '/api/public/hooks/daily-digest/status': typeof ApiPublicHooksDailyDigestStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mfa-challenge'
    | '/sitemap.xml'
    | '/admin'
    | '/bookmarks'
    | '/cockpit'
    | '/dashboard'
    | '/diagrams'
    | '/feeds'
    | '/meetings'
    | '/notes'
    | '/projects'
    | '/routines'
    | '/security'
    | '/snippets'
    | '/team'
    | '/templates'
    | '/tips'
    | '/todos'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/ingest-feeds'
    | '/api/public/hooks/monthly-tip'
    | '/api/public/hooks/daily-digest/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mfa-challenge'
    | '/sitemap.xml'
    | '/admin'
    | '/bookmarks'
    | '/cockpit'
    | '/dashboard'
    | '/diagrams'
    | '/feeds'
    | '/meetings'
    | '/notes'
    | '/projects'
    | '/routines'
    | '/security'
    | '/snippets'
    | '/team'
    | '/templates'
    | '/tips'
    | '/todos'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/ingest-feeds'
    | '/api/public/hooks/monthly-tip'
    | '/api/public/hooks/daily-digest/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/mfa-challenge'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/bookmarks'
    | '/_authenticated/cockpit'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagrams'
    | '/_authenticated/feeds'
    | '/_authenticated/meetings'
    | '/_authenticated/notes'
    | '/_authenticated/projects'
    | '/_authenticated/routines'
    | '/_authenticated/security'
    | '/_authenticated/snippets'
    | '/_authenticated/team'
    | '/_authenticated/templates'
    | '/_authenticated/tips'
    | '/_authenticated/todos'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/ingest-feeds'
    | '/api/public/hooks/monthly-tip'
    | '/api/public/hooks/daily-digest/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksDailyDigestRoute: typeof ApiPublicHooksDailyDigestRouteWithChildren
  ApiPublicHooksIngestFeedsRoute: typeof ApiPublicHooksIngestFeedsRoute
  ApiPublicHooksMonthlyTipRoute: typeof ApiPublicHooksMonthlyTipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-challenge': {
      id: '/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tips': {
      id: '/_authenticated/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof AuthenticatedTipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/snippets': {
      id: '/_authenticated/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof AuthenticatedSnippetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routines': {
      id: '/_authenticated/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AuthenticatedRoutinesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feeds': {
      id: '/_authenticated/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof AuthenticatedFeedsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagrams': {
      id: '/_authenticated/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof AuthenticatedDiagramsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cockpit': {
      id: '/_authenticated/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof AuthenticatedCockpitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/monthly-tip': {
      id: '/api/public/hooks/monthly-tip'
      path: '/api/public/hooks/monthly-tip'
      fullPath: '/api/public/hooks/monthly-tip'
      preLoaderRoute: typeof ApiPublicHooksMonthlyTipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-feeds': {
      id: '/api/public/hooks/ingest-feeds'
      path: '/api/public/hooks/ingest-feeds'
      fullPath: '/api/public/hooks/ingest-feeds'
      preLoaderRoute: typeof ApiPublicHooksIngestFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-digest': {
      id: '/api/public/hooks/daily-digest'
      path: '/api/public/hooks/daily-digest'
      fullPath: '/api/public/hooks/daily-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-digest/status': {
      id: '/api/public/hooks/daily-digest/status'
      path: '/status'
      fullPath: '/api/public/hooks/daily-digest/status'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestStatusRouteImport
      parentRoute: typeof ApiPublicHooksDailyDigestRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedCockpitRoute: typeof AuthenticatedCockpitRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagramsRoute: typeof AuthenticatedDiagramsRoute
  AuthenticatedFeedsRoute: typeof AuthenticatedFeedsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRoutinesRoute: typeof AuthenticatedRoutinesRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSnippetsRoute: typeof AuthenticatedSnippetsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTipsRoute: typeof AuthenticatedTipsRoute
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedCockpitRoute: AuthenticatedCockpitRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagramsRoute: AuthenticatedDiagramsRoute,
  AuthenticatedFeedsRoute: AuthenticatedFeedsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRoutinesRoute: AuthenticatedRoutinesRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSnippetsRoute: AuthenticatedSnippetsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTipsRoute: AuthenticatedTipsRoute,
  AuthenticatedTodosRoute: AuthenticatedTodosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicHooksDailyDigestRouteChildren {
  ApiPublicHooksDailyDigestStatusRoute: typeof ApiPublicHooksDailyDigestStatusRoute
}

const ApiPublicHooksDailyDigestRouteChildren: ApiPublicHooksDailyDigestRouteChildren =
  {
    ApiPublicHooksDailyDigestStatusRoute: ApiPublicHooksDailyDigestStatusRoute,
  }

const ApiPublicHooksDailyDigestRouteWithChildren =
  ApiPublicHooksDailyDigestRoute._addFileChildren(
    ApiPublicHooksDailyDigestRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksDailyDigestRoute: ApiPublicHooksDailyDigestRouteWithChildren,
  ApiPublicHooksIngestFeedsRoute: ApiPublicHooksIngestFeedsRoute,
  ApiPublicHooksMonthlyTipRoute: ApiPublicHooksMonthlyTipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
